#!/usr/bin/env python
from __future__ import print_function

import roslib
roslib.load_manifest('opencvtest')
import sys
import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
rospy.init_node('orbbec_astra_to_opencv')
image_sub = rospy.Subscriber("/camera/rgb/image_rect_color",Image)
bridge = CvBridge()
cv_image = bridge.imgmsg_to_cv2(Image, "bgr8")

print("Starting")

(rows,cols,channels) = cv_image.shape
if cols > 60 and rows > 60 :
	cv2.circle(cv_image, (50,50), 10, 255)
	cv2.imshow("Image window", cv_image)
	cv2.waitKey(3)
print("??")
