#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import String
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint

def talker():
    pub = rospy.Publisher('/cmd_joint_traj', JointTrajectory, queue_size=10)
    rospy.init_node('run_single_motor_node', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
	point = JointTrajectoryPoint()
	point.velocities = [-1, 1]
	message = JointTrajectory()
	message.joint_names = ['wheel_back_left_joint', 'wheel_front_left_joint']
	message.points = [point]
        pub.publish(message)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
